<!-- Generated by Trae Work -->
<template>
  <div class="storyboard-scene" :class="{ 'sb-global-glitch': globalGlitch }">
    <div class="sb-scanlines" />
    <div class="sb-noise" />

    <div
      v-for="win in windows"
      :key="win.key"
      class="sb-window"
      :class="[
        'sb-' + win.key,
        { 'is-on': hasScene(win.key), 'is-empty': !getScene(win.key), 'is-glitch': getState(win.key).glitch }
      ]"
      :style="{ '--c': win.themeColor, '--g': win.glowColor, '--b': win.borderColor, '--d': win.delay + 'ms' }"
    >
      <!-- 霓虹边框 -->
      <div class="sb-neon" />

      <!-- 色差分离层 -->
      <div class="sb-chroma" />

      <!-- 标签栏 -->
      <div class="sb-topbar">
        <span class="sb-ico">{{ win.icon }}</span>
        <span class="sb-txt">{{ win.label }}</span>
        <span class="sb-sub">{{ win.subtitle }}</span>
        <span class="sb-yr">{{ currentYear }}</span>
        <span v-if="hasScene(win.key)" class="sb-rec" />
      </div>

      <!-- 舞台 -->
      <div class="sb-stage">
        <div class="sb-vignette" />

        <!-- 漂浮环境粒子 -->
        <div class="sb-particles">
          <span
            v-for="i in particles"
            :key="i"
            class="sb-particle"
            :style="{ '--i': i, '--dur': (6 + Math.random() * 8) + 's', '--delay': (Math.random() * 5) + 's' }"
          />
        </div>

        <!-- 待机 -->
        <div v-if="!getScene(win.key)" class="sb-standby">
          <div class="sb-standby-dot" />
          <div class="sb-standby-line" />
          <div class="sb-standby-text">STANDBY</div>
        </div>

        <!-- 旧场景淡出 -->
        <div
          v-if="getState(win.key).prevScene && !getState(win.key).visible"
          class="sb-art-wrap sb-art-old"
        >
          <div class="sb-art-scale" :style="{ width: CANVAS_PX_W + 'px', height: CANVAS_PX_H + 'px' }">
            <div
              class="sb-art"
              :style="getFrameStyle(getState(win.key).prevScene!, 0)"
            />
          </div>
        </div>

        <!-- 当前主场景（帧动画） -->
        <div
          v-if="getScene(win.key)"
          class="sb-art-wrap"
          :class="{ 'sb-in': getState(win.key).visible, 'sb-new': getState(win.key).isNew }"
        >
          <div
            class="sb-art-scale"
            :class="[
              getState(win.key).isNew ? ('sb-anim-' + getScene(win.key)!.animIn) : '',
              sceneEffectClass(getScene(win.key))
            ]"
            :style="{ width: CANVAS_PX_W + 'px', height: CANVAS_PX_H + 'px' }"
          >
            <div
              class="sb-art"
              :style="getFrameStyle(getScene(win.key)!, getCurrentFrame(win.key))"
            />
            <!-- 场景特效叠加层 -->
            <div
              v-if="sceneEffectClass(getScene(win.key))"
              class="sb-effect-layer"
              :class="sceneEffectClass(getScene(win.key))"
            />
          </div>
        </div>

        <!-- 粒子爆发（新事件触发时） -->
        <div v-if="getState(win.key).burst" class="sb-burst">
          <span v-for="i in 16" :key="i" class="sb-burst-p" :style="{ '--i': i }" />
        </div>

        <!-- 光晕 -->
        <div v-if="getScene(win.key) && getState(win.key).visible" class="sb-glow" />
      </div>

      <!-- 场景名 -->
      <div class="sb-name" :class="{ 'sb-name-on': getScene(win.key) && getState(win.key).visible }">
        <span v-if="getScene(win.key)" class="sb-name-text">▸ {{ getScene(win.key)!.name }}</span>
      </div>

      <div v-if="win.key !== 'family'" class="sb-sep" />
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * 三分镜像素场景组件 v5 - 开罗游戏风格单年版
 *
 * 三个窗口并列：💼事业(绿) / ☕生活(青) / 🏠家庭(粉)
 * 当年触发的剧情事件，次年在对应窗口展示像素动画演绎。
 *
 * v5核心改进：
 * - 单年播放模式：每年新场景完全替换旧场景，不累积残影
 * - 24x20像素画布，Q版小人有表情有动作
 * - 多帧循环动画：每帧间隔frameDelay毫秒，小人会动
 * - 开罗游戏风格：人物跳跃、举杯、走路、打字等动作
 * - 保留CRT扫描线、噪点、霓虹边框、漂浮粒子
 * - 入场动画 + 持续微动效
 */

import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { useGameStore } from '../../store/game.store.js'
import { getSceneById, type StoryboardScene } from '../../data/storyboard-scenes.js'

const store = useGameStore()

// ================================================================
//  分镜队列（单年模式：每个分类只有1个当前场景id）
// ================================================================

const storyboards = computed(() => {
  const sb = (store as any).pendingStoryboards
  if (!sb) return { family: [], life: [], career: [] }
  return {
    family: (sb.family || []) as string[],
    life: (sb.life || []) as string[],
    career: (sb.career || []) as string[],
  }
})

// 年份显示
const currentYear = computed(() => {
  const age = store.state.currentAge
  return 2024 + (age - 22)
})

// ================================================================
//  窗口配置
// ================================================================
interface WindowConfig {
  key: 'family' | 'life' | 'career'
  icon: string
  label: string
  subtitle: string
  themeColor: string
  glowColor: string
  borderColor: string
  delay: number
}

const windows: WindowConfig[] = [
  { key: 'career', icon: '💼', label: '事业', subtitle: 'CAREER', themeColor: '#00ff88', glowColor: 'rgba(0,255,136,0.5)', borderColor: 'rgba(0,255,136,0.12)', delay: 0 },
  { key: 'life',   icon: '☕', label: '生活', subtitle: 'LIFE',   themeColor: '#00d4ff', glowColor: 'rgba(0,212,255,0.5)', borderColor: 'rgba(0,212,255,0.12)', delay: 180 },
  { key: 'family', icon: '🏠', label: '家庭', subtitle: 'FAMILY', themeColor: '#ff8ab8', glowColor: 'rgba(255,138,184,0.5)', borderColor: 'rgba(255,138,184,0.12)', delay: 360 },
]

// ================================================================
//  像素渲染（24x20画布，多帧）
// ================================================================

const PIXEL_SIZE = 5
const CANVAS_W = 24
const CANVAS_H = 20
const CANVAS_PX_W = CANVAS_W * PIXEL_SIZE
const CANVAS_PX_H = CANVAS_H * PIXEL_SIZE

function buildFrameShadows(frame: number[][], palette: string[]): string {
  const shadows: string[] = []
  for (let row = 0; row < frame.length && row < CANVAS_H; row++) {
    for (let col = 0; col < frame[row].length && col < CANVAS_W; col++) {
      const ci = frame[row][col]
      if (ci === 0) continue
      const color = palette[ci]
      if (!color || color === 'transparent') continue
      // box-shadow相对于元素自身位置，col=0/row=0时阴影在元素正下方
      shadows.push(`${col * PIXEL_SIZE}px ${row * PIXEL_SIZE}px 0 0 ${color}`)
    }
  }
  return shadows.join(', ')
}

function getFrameStyle(scene: StoryboardScene, frameIndex: number) {
  const frame = scene.frames[frameIndex % scene.frames.length]
  return {
    width: PIXEL_SIZE + 'px',
    height: PIXEL_SIZE + 'px',
    boxShadow: buildFrameShadows(frame, scene.palette),
  }
}

// ================================================================
//  帧动画循环
// ================================================================

const currentFrames = ref<Record<string, number>>({
  family: 0, life: 0, career: 0,
})

let frameTimers: Record<string, number | null> = {
  family: null, life: null, career: null,
}

function startFrameLoop(key: string, scene: StoryboardScene) {
  stopFrameLoop(key)
  if (scene.frames.length <= 1) return
  currentFrames.value[key] = 0
  const tick = () => {
    currentFrames.value[key] = (currentFrames.value[key] + 1) % scene.frames.length
    frameTimers[key] = window.setTimeout(tick, scene.frameDelay)
  }
  frameTimers[key] = window.setTimeout(tick, scene.frameDelay)
}

function stopFrameLoop(key: string) {
  if (frameTimers[key]) {
    clearTimeout(frameTimers[key]!)
    frameTimers[key] = null
  }
}

function stopAllFrameLoops() {
  for (const key of ['family', 'life', 'career']) {
    stopFrameLoop(key)
  }
}

function getCurrentFrame(key: string): number {
  return currentFrames.value[key] || 0
}

// ================================================================
//  动画状态
// ================================================================

interface WinState {
  scene: StoryboardScene | null
  prevScene: StoryboardScene | null
  visible: boolean
  burst: boolean
  glitch: boolean
  isNew: boolean
}

const states = ref<Record<string, WinState>>({
  family:  { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false },
  life:    { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false },
  career:  { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false },
})

const prevSceneIds = ref<Record<string, string | null>>({
  family: null, life: null, career: null,
})

// 全局CRT故障效果
const globalGlitch = ref(false)
let glitchTimer: number | null = null

function scheduleGlitch() {
  if (glitchTimer) clearTimeout(glitchTimer)
  const nextGlitch = 8000 + Math.random() * 17000
  glitchTimer = window.setTimeout(() => {
    globalGlitch.value = true
    setTimeout(() => { globalGlitch.value = false }, 180)
    scheduleGlitch()
  }, nextGlitch)
}

function playStoryboards() {
  for (const win of windows) {
    const key = win.key
    const idList = (storyboards.value as any)[key] as string[]
    const currentId = idList.length > 0 ? idList[idList.length - 1] : null
    const currentScene = currentId ? (getSceneById(currentId) || null) : null
    const st = states.value[key]
    const prevId = prevSceneIds.value[key]

    if (currentId === prevId) {
      st.visible = true
      st.isNew = false
      continue
    }

    // 新事件到来：停止旧帧循环，准备切换
    stopFrameLoop(key)
    st.prevScene = st.scene
    st.visible = false
    st.isNew = true
    currentFrames.value[key] = 0

    setTimeout(() => {
      st.scene = currentScene
      prevSceneIds.value[key] = currentId
      st.visible = true
      if (currentScene) {
        // 启动帧动画循环
        startFrameLoop(key, currentScene)
        st.burst = true
        setTimeout(() => { st.burst = false }, 900)
        setTimeout(() => {
          st.glitch = true
          setTimeout(() => { st.glitch = false }, 220)
        }, 500 + win.delay)
        setTimeout(() => { st.isNew = false }, 2000)
      }
    }, win.delay + 150)
  }
}

watch(() => store.state.currentAge, () => { setTimeout(playStoryboards, 400) })
watch(() => [storyboards.value.family.length, storyboards.value.life.length, storyboards.value.career.length], () => { setTimeout(playStoryboards, 400) })
onMounted(() => {
  setTimeout(playStoryboards, 600)
  scheduleGlitch()
})
onUnmounted(() => {
  if (glitchTimer) clearTimeout(glitchTimer)
  stopAllFrameLoops()
})

// ================================================================
//  辅助函数
// ================================================================

function getState(key: string): WinState {
  return states.value[key] || { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false }
}

function getScene(key: string): StoryboardScene | null {
  return getState(key).scene
}

function hasScene(key: string): boolean {
  return getScene(key) !== null
}

// 获取场景专属特效class
function sceneEffectClass(scene: StoryboardScene | null): string {
  if (!scene) return ''
  const effects: Record<string, string> = {
    // 家庭
    house: 'sb-effect-smoke',
    car: 'sb-effect-speed',
    marriage: 'sb-effect-hearts',
    confess: 'sb-effect-hearts',
    dating: 'sb-effect-hearts',
    baby: 'sb-effect-twinkle',
    couple_fight: 'sb-effect-lightning',
    divorce: 'sb-effect-broken',
    breakup: 'sb-effect-broken',
    parents: 'sb-effect-hearts',
    parent_sick: 'sb-effect-heartbeat',
    play_kid: 'sb-effect-stars-small',
    midnight_baby: 'sb-effect-zzz',
    anniversary: 'sb-effect-flame',
    grandchildren: 'sb-effect-stars-small',
    old_couple_tv: 'sb-effect-tv',
    blind_date: 'sb-effect-question',
    // 生活
    sickness: 'sb-effect-heartbeat',
    move: 'sb-effect-speed',
    lottery: 'sb-effect-coins',
    lend_money: 'sb-effect-coins',
    travel: 'sb-effect-clouds',
    friend_drink: 'sb-effect-bubbles',
    pet: 'sb-effect-heart-small',
    phone: 'sb-effect-screen',
    gym: 'sb-effect-flex',
    fishing: 'sb-effect-water',
    square_dance: 'sb-effect-notes',
    reading: 'sb-effect-book',
    // 事业
    work: 'sb-effect-screen',
    promotion: 'sb-effect-stars',
    startup: 'sb-effect-flames',
    fired: 'sb-effect-paper-fall',
    bankruptcy: 'sb-effect-shake',
    retirement_party: 'sb-effect-confetti',
    job_hop: 'sb-effect-stars',
    bonus: 'sb-effect-coins',
    overtime: 'sb-effect-moon',
    investment: 'sb-effect-chart',
    burnout: 'sb-effect-fog',
  }
  return effects[scene.id] || ''
}

// 粒子数量
const PARTICLES_PER_WIN = 6
const particles = Array.from({ length: PARTICLES_PER_WIN }, (_, i) => i)
</script>

<style scoped>
/* ===== 容器 ===== */
.storyboard-scene {
  position: absolute;
  inset: 0;
  display: flex;
  gap: 0;
  background: #050608;
  overflow: hidden;
}

.sb-scanlines {
  position: absolute;
  inset: 0;
  background: repeating-linear-gradient(
    0deg, transparent, transparent 1px,
    rgba(0,0,0,0.12) 1px, rgba(0,0,0,0.12) 2px
  );
  pointer-events: none;
  z-index: 20;
  opacity: 0.6;
}

/* 噪点层 */
.sb-noise {
  position: absolute;
  inset: 0;
  z-index: 19;
  pointer-events: none;
  opacity: 0.03;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
  animation: noiseShift 0.5s steps(2) infinite;
}
@keyframes noiseShift {
  0% { transform: translate(0, 0); }
  25% { transform: translate(-1px, 1px); }
  50% { transform: translate(1px, -1px); }
  75% { transform: translate(-1px, -1px); }
  100% { transform: translate(1px, 1px); }
}

/* 全局故障 */
.sb-global-glitch {
  animation: globalGlitch 0.18s steps(2);
}
.sb-global-glitch .sb-window {
  animation: winGlitch 0.18s steps(2);
}
@keyframes globalGlitch {
  0% { transform: translate(0); filter: hue-rotate(0deg); }
  20% { transform: translate(-2px, 1px); filter: hue-rotate(30deg); }
  40% { transform: translate(2px, -1px); filter: hue-rotate(-30deg); }
  60% { transform: translate(-1px, 2px); filter: hue-rotate(15deg); }
  80% { transform: translate(1px, -2px); filter: hue-rotate(-15deg); }
  100% { transform: translate(0); filter: hue-rotate(0deg); }
}
@keyframes winGlitch {
  0%,100% { transform: skewX(0deg); }
  25% { transform: skewX(-2deg); }
  75% { transform: skewX(2deg); }
}

/* ===== 窗口 ===== */
.sb-window {
  flex: 1;
  position: relative;
  display: flex;
  flex-direction: column;
  background: linear-gradient(180deg, rgba(10,12,16,0.95) 0%, rgba(5,6,8,0.98) 100%);
  border-right: 1px solid var(--b);
  overflow: hidden;
  transition: flex 0.6s ease;
}
.sb-window:last-child { border-right: none; }
.sb-window.is-on {
  background: linear-gradient(180deg, rgba(12,15,20,0.9) 0%, rgba(6,8,12,0.95) 100%);
}

/* 霓虹边框 */
.sb-neon {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 10;
  opacity: 0;
  transition: opacity 0.6s;
  box-shadow: inset 0 0 0 1px var(--c), inset 0 0 20px var(--g);
}
.sb-window.is-on .sb-neon { opacity: 0.7; animation: neonBreath 3s ease-in-out infinite; }
@keyframes neonBreath {
  0%,100% { opacity: 0.5; }
  50% { opacity: 0.85; }
}

/* 色差分离 */
.sb-chroma {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 11;
  opacity: 0;
  background:
    linear-gradient(90deg, rgba(255,0,80,0.03) 0%, transparent 40%, transparent 60%, rgba(0,200,255,0.03) 100%);
  mix-blend-mode: screen;
}
.sb-window.is-glitch .sb-chroma {
  opacity: 1;
  animation: chromaShift 0.22s steps(3);
}
@keyframes chromaShift {
  0% { transform: translateX(0); }
  33% { transform: translateX(-2px); }
  66% { transform: translateX(2px); }
  100% { transform: translateX(0); }
}

/* 顶栏 */
.sb-topbar {
  position: relative;
  z-index: 12;
  display: flex;
  align-items: center;
  gap: 5px;
  padding: 4px 7px;
  background: linear-gradient(180deg, rgba(0,0,0,0.5) 0%, transparent 100%);
  border-bottom: 1px solid var(--b);
  font-family: 'Courier New', 'Consolas', monospace;
  font-size: 9px;
  letter-spacing: 0.5px;
  flex-shrink: 0;
}
.sb-ico { font-size: 10px; }
.sb-txt { color: var(--c); font-weight: bold; font-size: 10px; }
.sb-sub { color: rgba(255,255,255,0.3); font-size: 8px; letter-spacing: 1px; }
.sb-yr {
  margin-left: auto;
  color: rgba(255,255,255,0.35);
  font-size: 8px;
}
.sb-rec {
  width: 6px; height: 6px;
  border-radius: 50%;
  background: #ff3355;
  animation: recBlink 1.2s ease-in-out infinite;
  box-shadow: 0 0 6px #ff3355;
}
@keyframes recBlink {
  0%,100% { opacity: 1; }
  50% { opacity: 0.3; }
}

/* ===== 舞台 ===== */
.sb-stage {
  flex: 1;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  min-height: 0;
}

.sb-vignette {
  position: absolute;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background: radial-gradient(ellipse at center, transparent 40%, rgba(0,0,0,0.5) 100%);
}

/* 漂浮粒子 */
.sb-particles {
  position: absolute;
  inset: 0;
  z-index: 2;
  pointer-events: none;
  overflow: hidden;
}
.sb-particle {
  position: absolute;
  width: 2px;
  height: 2px;
  background: var(--c);
  border-radius: 50%;
  opacity: 0;
  left: calc(10% + var(--i) * 14%);
  bottom: -5px;
  animation: particleFloat var(--dur) ease-in-out infinite;
  animation-delay: var(--delay);
  box-shadow: 0 0 4px var(--c);
}
.sb-window.is-empty .sb-particle { display: none; }
@keyframes particleFloat {
  0% { transform: translateY(0) translateX(0); opacity: 0; }
  10% { opacity: 0.4; }
  50% { transform: translateY(-60px) translateX(5px); opacity: 0.6; }
  90% { opacity: 0.2; }
  100% { transform: translateY(-120px) translateX(-3px); opacity: 0; }
}

/* 待机 */
.sb-standby {
  position: relative;
  z-index: 4;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  opacity: 0.25;
}
.sb-standby-dot {
  width: 8px; height: 8px;
  border-radius: 50%;
  border: 1px solid var(--c);
  animation: standbyPulse 2s ease-in-out infinite;
}
@keyframes standbyPulse {
  0%,100% { opacity: 0.3; box-shadow: 0 0 4px var(--c); }
  50% { opacity: 0.8; box-shadow: 0 0 12px var(--c); }
}
.sb-standby-line {
  width: 40px; height: 1px;
  background: linear-gradient(90deg, transparent, var(--c), transparent);
}
.sb-standby-text {
  font-family: 'Courier New', monospace;
  font-size: 7px;
  color: var(--c);
  letter-spacing: 2px;
}

/* 像素艺术画布 */
.sb-art-wrap {
  position: absolute;
  z-index: 5;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
}
.sb-art-wrap.sb-in { opacity: 1; transition: opacity 0.3s ease; }
.sb-art-wrap.sb-new { transition: none; }
.sb-art-wrap.sb-art-old {
  z-index: 4;
  opacity: 0;
  animation: oldFadeOut 0.6s ease-out forwards;
}
@keyframes oldFadeOut {
  0% { opacity: 1; transform: scale(1); filter: brightness(1); }
  100% { opacity: 0; transform: scale(0.9) translateY(5px); filter: brightness(0.3) blur(2px); }
}
.sb-art-wrap.sb-new .sb-art-scale {
  animation: newJoin 0.9s cubic-bezier(0.34,1.56,0.64,1);
}
@keyframes newJoin {
  0% { transform: scale(0.3) rotate(-8deg); filter: brightness(3); }
  40% { transform: scale(1.15) rotate(2deg); filter: brightness(1.8); }
  70% { transform: scale(0.95) rotate(-1deg); filter: brightness(1.2); }
  100% { transform: scale(1) rotate(0deg); filter: brightness(1); }
}

.sb-art-scale {
  position: relative;
  transform-origin: center bottom;
}
.sb-art {
  position: absolute;
  left: 0;
  top: 0;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
}

/* 入场动画 - 应用在sb-art-scale上 */
.sb-art-scale.sb-anim-fade {
  opacity: 0;
  animation: aFade 0.7s ease-out forwards;
}
@keyframes aFade {
  to { opacity: 1; }
}

.sb-art-scale.sb-anim-rise {
  opacity: 0;
  transform: translateY(12px);
  animation: aRise 0.8s cubic-bezier(0.22,1,0.36,1) forwards;
}
@keyframes aRise {
  to { opacity: 1; transform: translateY(0); }
}

.sb-art-scale.sb-anim-pop {
  opacity: 0;
  transform: scale(0.1);
  animation: aPop 0.8s cubic-bezier(0.34,1.56,0.64,1) forwards;
}
@keyframes aPop {
  0%   { opacity: 0; transform: scale(0.1); filter: brightness(5); }
  50%  { opacity: 1; transform: scale(1.25); filter: brightness(2); }
  72%  { transform: scale(0.9); filter: brightness(1.4); }
  85%  { transform: scale(1.05); filter: brightness(1.1); }
  100% { opacity: 1; transform: scale(1); filter: brightness(1); }
}

.sb-art-scale.sb-anim-slide {
  opacity: 0;
  transform: translateX(24px);
  animation: aSlide 0.85s cubic-bezier(0.22,1,0.36,1) forwards;
}
@keyframes aSlide {
  0%   { opacity: 0; transform: translateX(24px); filter: blur(3px); }
  100% { opacity: 1; transform: translateX(0); filter: blur(0); }
}

.sb-art-scale.sb-anim-blink {
  opacity: 0;
  animation: aBlink 0.5s steps(5) forwards;
}
@keyframes aBlink {
  0%   { opacity: 0; }
  40%  { opacity: 1; }
  60%  { opacity: 0; }
  80%  { opacity: 1; }
  100% { opacity: 1; }
}

.sb-art-scale.sb-anim-shake {
  opacity: 0;
  transform: scale(0.85);
  animation: aShakeIn 0.5s ease-out forwards, aShake 0.3s ease-in-out 0.6s 3;
}
@keyframes aShakeIn {
  0%   { opacity: 0; transform: scale(0.85); }
  100% { opacity: 1; transform: scale(1); }
}
@keyframes aShake {
  0%,100% { transform: translateX(0); }
  20%     { transform: translateX(-3px); }
  40%     { transform: translateX(3px); }
  60%     { transform: translateX(-2px); }
  80%     { transform: translateX(2px); }
}

.sb-art-scale.sb-anim-bounce {
  opacity: 0;
  transform: translateY(20px) scale(0.8);
  animation: aBounce 0.9s cubic-bezier(0.34,1.56,0.64,1) forwards;
}
@keyframes aBounce {
  0%   { opacity: 0; transform: translateY(20px) scale(0.8); }
  50%  { opacity: 1; transform: translateY(-5px) scale(1.1); }
  70%  { transform: translateY(3px) scale(0.95); }
  85%  { transform: translateY(-2px) scale(1.02); }
  100% { opacity: 1; transform: translateY(0) scale(1); }
}

/* 持续微动效：开罗游戏经典小人弹跳+呼吸（入场动画完成后启动） */
.sb-art-wrap.sb-in .sb-art-scale {
  animation: idleBounce 2s ease-in-out infinite;
  animation-delay: 1s;
}
@keyframes idleBounce {
  0%,100% { transform: translateY(0) scale(1); filter: drop-shadow(0 3px 4px rgba(0,0,0,0.5)) drop-shadow(0 0 5px var(--g)) brightness(1); }
  40%     { transform: translateY(-3px) scale(1.02, 0.98); filter: drop-shadow(0 6px 8px rgba(0,0,0,0.4)) drop-shadow(0 0 10px var(--g)) brightness(1.1); }
  60%     { transform: translateY(-3px) scale(1.02, 0.98); filter: drop-shadow(0 6px 8px rgba(0,0,0,0.4)) drop-shadow(0 0 10px var(--g)) brightness(1.1); }
}

/* 粒子爆发 */
.sb-burst {
  position: absolute;
  z-index: 8;
  inset: 0;
  pointer-events: none;
}
.sb-burst-p {
  position: absolute;
  left: 50%;
  top: 50%;
  width: 4px;
  height: 4px;
  background: var(--c);
  border-radius: 50%;
  box-shadow: 0 0 8px var(--c), 0 0 16px var(--g);
  animation: burstOut 0.9s ease-out forwards;
  --angle: calc(var(--i) * 22.5deg);
  --dist: 40px;
}
@keyframes burstOut {
  0% {
    transform: translate(-50%, -50%) rotate(var(--angle)) translateX(0) scale(1);
    opacity: 1;
  }
  100% {
    transform: translate(-50%, -50%) rotate(var(--angle)) translateX(var(--dist)) scale(0);
    opacity: 0;
  }
}

/* 光晕 */
.sb-glow {
  position: absolute;
  z-index: 0;
  width: 100px;
  height: 100px;
  border-radius: 50%;
  background: radial-gradient(circle, var(--g) 0%, transparent 70%);
  opacity: 0.3;
  animation: glowPulse 3s ease-in-out infinite;
  pointer-events: none;
  filter: blur(10px);
}
@keyframes glowPulse {
  0%,100% { opacity: 0.2; transform: scale(1); }
  50% { opacity: 0.4; transform: scale(1.2); }
}

/* 场景名 */
.sb-name {
  position: relative;
  z-index: 12;
  padding: 3px 7px;
  border-top: 1px solid var(--b);
  background: linear-gradient(0deg, rgba(0,0,0,0.6) 0%, transparent 100%);
  min-height: 18px;
  flex-shrink: 0;
}
.sb-name-text {
  font-family: 'Courier New', monospace;
  font-size: 8px;
  color: rgba(255,255,255,0.4);
  opacity: 0;
  transform: translateY(4px);
  transition: all 0.5s ease;
  letter-spacing: 0.5px;
}
.sb-name-on .sb-name-text {
  opacity: 1;
  transform: translateY(0);
  color: var(--c);
  text-shadow: 0 0 8px var(--g);
}

.sb-sep {
  position: absolute;
  right: 0;
  top: 10%;
  bottom: 10%;
  width: 1px;
  background: linear-gradient(180deg, transparent, rgba(255,255,255,0.08), transparent);
  z-index: 15;
}

/* ===== 场景专属特效 ===== */
.sb-effect-layer {
  position: absolute;
  inset: 0;
  pointer-events: none;
}

/* 炊烟 */
.sb-effect-smoke::after {
  content: '';
  position: absolute;
  width: 6px; height: 6px;
  background: rgba(200,200,200,0.3);
  border-radius: 50%;
  top: -10px; right: 25px;
  animation: smokeRise 3s ease-out infinite;
}
@keyframes smokeRise {
  0% { transform: translateY(0) scale(1); opacity: 0.5; }
  100% { transform: translateY(-25px) scale(3); opacity: 0; }
}

/* 火焰 */
.sb-effect-flame::after, .sb-effect-flames::after {
  content: '';
  position: absolute;
  width: 6px; height: 8px;
  background: radial-gradient(ellipse at bottom, #ffdd00, #ff6600, transparent);
  border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%;
  top: -12px;
  animation: flameFlicker 0.4s ease-in-out infinite alternate;
  filter: blur(0.5px);
}
.sb-effect-flames::after { left: 20px; }
.sb-effect-flame::after { left: 50%; margin-left: -3px; }
@keyframes flameFlicker {
  0% { transform: scale(1) rotate(-2deg); opacity: 0.9; }
  100% { transform: scale(1.2) rotate(3deg); opacity: 1; }
}

/* 爱心飘升 */
.sb-effect-hearts::after, .sb-effect-heart-small::after {
  content: '♥';
  position: absolute;
  font-size: 10px;
  color: var(--c);
  top: 0; left: 50%;
  margin-left: -5px;
  opacity: 0;
  animation: heartFloat 2.5s ease-in-out infinite;
  text-shadow: 0 0 8px var(--c);
}
.sb-effect-heart-small::after { font-size: 8px; }
@keyframes heartFloat {
  0% { transform: translateY(0) scale(0.5); opacity: 0; }
  20% { opacity: 0.9; }
  100% { transform: translateY(-40px) scale(1.3); opacity: 0; }
}

/* 星星闪烁 */
.sb-effect-twinkle::before, .sb-effect-twinkle::after {
  content: '✦';
  position: absolute;
  font-size: 8px;
  color: #ffdd88;
  animation: twinkle 1.5s ease-in-out infinite;
  text-shadow: 0 0 8px #ffdd88;
}
.sb-effect-twinkle::before { top: -8px; left: -8px; animation-delay: 0s; }
.sb-effect-twinkle::after { top: -10px; right: -5px; animation-delay: 0.8s; }
@keyframes twinkle {
  0%,100% { opacity: 0.2; transform: scale(0.7); }
  50% { opacity: 1; transform: scale(1.3); }
}

/* 心跳 */
.sb-effect-heartbeat::after {
  content: '♥';
  position: absolute;
  font-size: 14px;
  color: #ff4466;
  top: 50%; left: 50%;
  margin: -25px 0 0 -7px;
  animation: heartbeat 0.8s ease-in-out infinite;
  text-shadow: 0 0 10px #ff4466;
  opacity: 0.6;
}
@keyframes heartbeat {
  0%,100% { transform: scale(1); }
  15% { transform: scale(1.4); }
  30% { transform: scale(1); }
  45% { transform: scale(1.3); }
}

/* 气泡 */
.sb-effect-bubbles::after {
  content: '';
  position: absolute;
  width: 4px; height: 4px;
  border-radius: 50%;
  border: 1px solid rgba(255,255,255,0.5);
  bottom: 0; left: 50%;
  margin-left: -2px;
  animation: bubbleUp 1.8s ease-out infinite;
}
@keyframes bubbleUp {
  0% { transform: translateY(0) scale(1); opacity: 0.6; }
  100% { transform: translateY(-30px) scale(0.3); opacity: 0; }
}

/* 云朵 */
.sb-effect-clouds::before {
  content: '☁';
  position: absolute;
  font-size: 10px;
  top: -8px; left: -25px;
  color: rgba(255,255,255,0.3);
  animation: cloudDrift 7s linear infinite;
}
@keyframes cloudDrift {
  0% { transform: translateX(0); opacity: 0; }
  15% { opacity: 0.4; }
  85% { opacity: 0.4; }
  100% { transform: translateX(140px); opacity: 0; }
}

/* 水波纹 */
.sb-effect-water::after {
  content: '';
  position: absolute;
  width: 24px; height: 8px;
  bottom: -5px; left: 50%;
  margin-left: -12px;
  border: 1px solid rgba(0,150,255,0.4);
  border-radius: 50%;
  animation: waterRipple 2s ease-out infinite;
}
@keyframes waterRipple {
  0% { transform: scale(0.4); opacity: 0.8; }
  100% { transform: scale(2.2); opacity: 0; }
}

/* 音符 */
.sb-effect-notes::after {
  content: '♪';
  position: absolute;
  font-size: 10px;
  color: var(--c);
  top: -8px; right: 5px;
  opacity: 0;
  animation: noteFloat 2s ease-in-out infinite;
  text-shadow: 0 0 8px var(--c);
}
@keyframes noteFloat {
  0% { transform: translateY(0) rotate(0deg); opacity: 0; }
  30% { opacity: 0.8; }
  100% { transform: translateY(-25px) rotate(20deg); opacity: 0; }
}

/* 金币 */
.sb-effect-coins::before {
  content: '¥';
  position: absolute;
  font-size: 10px;
  color: #ffdd00;
  font-weight: bold;
  top: -12px; left: 50%;
  margin-left: -5px;
  animation: coinDrop 1.2s ease-in infinite;
  text-shadow: 0 0 8px #ffdd00;
}
@keyframes coinDrop {
  0% { transform: translateY(-15px) rotate(0deg); opacity: 0; }
  20% { opacity: 1; }
  100% { transform: translateY(35px) rotate(360deg); opacity: 0; }
}

/* 星星爆发 */
.sb-effect-stars::before, .sb-effect-stars-small::before {
  content: '★';
  position: absolute;
  color: #ffdd00;
  animation: starBurst 1.2s ease-out;
  text-shadow: 0 0 10px #ffdd00;
}
.sb-effect-stars::before { font-size: 14px; top: -10px; left: 50%; margin-left: -7px; }
.sb-effect-stars-small::before { font-size: 9px; top: -6px; left: 50%; margin-left: -4px; }
@keyframes starBurst {
  0% { transform: scale(0) rotate(0deg); opacity: 1; }
  40% { transform: scale(1.6) rotate(180deg); opacity: 1; }
  100% { transform: scale(0.4) rotate(360deg); opacity: 0; }
}

/* 闪电 */
.sb-effect-lightning::after {
  content: '⚡';
  position: absolute;
  font-size: 16px;
  top: -12px; left: 50%;
  margin-left: -8px;
  opacity: 0;
  animation: lightning 2.5s ease-in-out infinite;
  text-shadow: 0 0 12px #ffee00;
}
@keyframes lightning {
  0%,88%,100% { opacity: 0; }
  90% { opacity: 1; }
  92% { opacity: 0.2; }
  94% { opacity: 1; }
}

/* ZZZ */
.sb-effect-zzz::after {
  content: 'Z z';
  position: absolute;
  font-size: 9px;
  color: rgba(255,255,255,0.5);
  top: -10px; right: 5px;
  animation: zzzFloat 3s ease-out infinite;
}
@keyframes zzzFloat {
  0% { transform: translate(0,0) scale(0.8); opacity: 0; }
  30% { opacity: 0.6; }
  100% { transform: translate(10px,-20px) scale(1.3); opacity: 0; }
}

/* 碎心 */
.sb-effect-broken::after {
  content: '💔';
  position: absolute;
  font-size: 12px;
  top: 50%; left: 50%;
  margin: -20px 0 0 -8px;
  opacity: 0.7;
  animation: brokenShake 0.5s ease-in-out infinite;
}
@keyframes brokenShake {
  0%,100% { transform: translateX(0); }
  25% { transform: translateX(-2px); }
  75% { transform: translateX(2px); }
}

/* 其余特效的轻量光晕 */
.sb-effect-speed::after, .sb-effect-screen::after, .sb-effect-chart::after,
.sb-effect-shake::after, .sb-effect-paper-fall::after,
.sb-effect-fog::after, .sb-effect-flex::after,
.sb-effect-book::after, .sb-effect-tv::after {
  content: '';
  position: absolute;
  inset: 0;
  pointer-events: none;
  opacity: 0.15;
  background: radial-gradient(circle at center, var(--c) 0%, transparent 70%);
  animation: genericPulse 2.5s ease-in-out infinite;
}
@keyframes genericPulse {
  0%,100% { opacity: 0.08; }
  50% { opacity: 0.2; }
}

/* 问号（相亲） */
.sb-effect-question::after {
  content: '?';
  position: absolute;
  font-size: 14px;
  font-weight: bold;
  color: var(--c);
  top: -8px; left: 50%;
  margin-left: -5px;
  animation: questionBounce 1s ease-in-out infinite;
  text-shadow: 0 0 8px var(--c);
}
@keyframes questionBounce {
  0%,100% { transform: translateY(0) scale(1); opacity: 0.7; }
  50% { transform: translateY(-6px) scale(1.2); opacity: 1; }
}

/* 月亮（加班） */
.sb-effect-moon::before {
  content: '';
  position: absolute;
  width: 10px; height: 10px;
  border-radius: 50%;
  background: #ffeaa7;
  top: -5px; right: 5px;
  box-shadow: 0 0 12px #ffeaa7, 0 0 20px rgba(255,234,167,0.5);
  animation: moonGlow 3s ease-in-out infinite;
}
.sb-effect-moon::after {
  content: '';
  position: absolute;
  width: 8px; height: 8px;
  border-radius: 50%;
  background: #0a0d14;
  top: -7px; right: 3px;
}
@keyframes moonGlow {
  0%,100% { opacity: 0.8; box-shadow: 0 0 12px #ffeaa7, 0 0 20px rgba(255,234,167,0.5); }
  50% { opacity: 1; box-shadow: 0 0 18px #ffeaa7, 0 0 30px rgba(255,234,167,0.7); }
}

/* 彩带（退休派对） */
.sb-effect-confetti::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(circle at 20% 20%, #ff3d7f 2px, transparent 2px),
    radial-gradient(circle at 80% 15%, #00d4ff 2px, transparent 2px),
    radial-gradient(circle at 30% 80%, #ffd700 2px, transparent 2px),
    radial-gradient(circle at 70% 70%, #00ff88 2px, transparent 2px),
    radial-gradient(circle at 50% 10%, #c900ff 2px, transparent 2px);
  animation: confettiFall 2s ease-in-out infinite;
  opacity: 0.6;
}
@keyframes confettiFall {
  0% { transform: translateY(-5px); opacity: 0; }
  30% { opacity: 0.8; }
  100% { transform: translateY(10px); opacity: 0; }
}

/* ===== 响应式 ===== */
@media (max-width: 768px) {
  .sb-topbar { padding: 3px 5px; font-size: 7px; }
  .sb-ico { font-size: 8px; }
  .sb-txt { font-size: 8px; }
  .sb-sub { display: none; }
  .sb-name-text { font-size: 7px; }
}

@media (min-width: 1400px) {
  .sb-topbar { padding: 5px 10px; font-size: 10px; gap: 6px; }
  .sb-ico { font-size: 12px; }
  .sb-txt { font-size: 12px; }
  .sb-sub { font-size: 9px; }
  .sb-yr { font-size: 9px; }
  .sb-name { padding: 4px 10px; min-height: 22px; }
  .sb-name-text { font-size: 10px; }
  .sb-rec { width: 7px; height: 7px; }
}

@media (min-width: 1900px) {
  .sb-topbar { padding: 6px 12px; font-size: 11px; gap: 8px; }
  .sb-ico { font-size: 14px; }
  .sb-txt { font-size: 14px; }
  .sb-sub { font-size: 10px; }
  .sb-name-text { font-size: 11px; }
}
</style>
