<!-- Generated by Trae Work -->
<template>
  <div class="storyboard-scene" :class="{ 'sb-global-glitch': globalGlitch }">
    <div class="sb-scanlines" />
    <div class="sb-noise" />

    <div
      v-for="win in windows"
      :key="win.key"
      class="sb-window"
      :class="[
        'sb-' + win.key,
        { 'is-on': hasTrigger(win.key), 'is-empty': !getLatestScene(win.key), 'is-glitch': getState(win.key).glitch }
      ]"
      :style="{ '--c': win.themeColor, '--g': win.glowColor, '--b': win.borderColor, '--d': win.delay + 'ms' }"
    >
      <!-- 霓虹边框 -->
      <div class="sb-neon" />

      <!-- 色差分离层 -->
      <div class="sb-chroma" />

      <!-- 标签栏 -->
      <div class="sb-topbar">
        <span class="sb-ico">{{ win.icon }}</span>
        <span class="sb-txt">{{ win.label }}</span>
        <span class="sb-sub">{{ win.subtitle }}</span>
        <span class="sb-yr">{{ currentYear }}</span>
        <span v-if="hasTrigger(win.key)" class="sb-rec" />
        <span v-if="getHistoryCount(win.key) > 1" class="sb-count">{{ getHistoryCount(win.key) }}</span>
      </div>

      <!-- 舞台 -->
      <div class="sb-stage">
        <div class="sb-vignette" />

        <!-- 漂浮环境粒子 -->
        <div class="sb-particles">
          <span
            v-for="i in particles"
            :key="i"
            class="sb-particle"
            :style="{ '--i': i, '--dur': (6 + Math.random() * 8) + 's', '--delay': (Math.random() * 5) + 's' }"
          />
        </div>

        <!-- 记忆残影层（旧场景的半透明叠加，体现"累积"感） -->
        <div class="sb-memory-layer">
          <div
            v-for="(ghost, idx) in getGhostScenes(win.key)"
            :key="ghost.id + '-' + idx"
            class="sb-ghost"
            :class="'sb-ghost-' + idx"
            :style="getSceneStyle(ghost)"
          />
        </div>

        <!-- 待机 -->
        <div v-if="!getLatestScene(win.key)" class="sb-standby">
          <div class="sb-standby-dot" />
          <div class="sb-standby-line" />
          <div class="sb-standby-text">STANDBY</div>
        </div>

        <!-- 旧场景淡出 -->
        <div
          v-if="getState(win.key).prevScene && !getState(win.key).visible"
          class="sb-art-wrap sb-art-old"
        >
          <div class="sb-art-scale">
            <div
              class="sb-art"
              :style="getSceneStyle(getState(win.key).prevScene!)"
            />
          </div>
        </div>

        <!-- 当前主场景 -->
        <div
          v-if="getLatestScene(win.key)"
          class="sb-art-wrap"
          :class="{ 'sb-in': getState(win.key).visible, 'sb-new': getState(win.key).isNew }"
        >
          <div class="sb-art-scale">
            <div
              class="sb-art"
              :class="[
                'sb-anim-' + getLatestScene(win.key)!.animIn,
                idleClass(getLatestScene(win.key)),
                sceneEffectClass(getLatestScene(win.key))
              ]"
              :style="getSceneStyle(getLatestScene(win.key)!)"
            />
            <!-- 场景特效叠加层 -->
            <div
              v-if="sceneEffectClass(getLatestScene(win.key))"
              class="sb-effect-layer"
              :class="sceneEffectClass(getLatestScene(win.key))"
            />
          </div>
        </div>

        <!-- 粒子爆发（新事件触发时） -->
        <div v-if="getState(win.key).burst" class="sb-burst">
          <span v-for="i in 16" :key="i" class="sb-burst-p" :style="{ '--i': i }" />
        </div>

        <!-- 光晕 -->
        <div v-if="getLatestScene(win.key) && getState(win.key).visible" class="sb-glow" />

        <!-- 记忆轨迹条（底部小圆点，每个点代表一个历史事件） -->
        <div v-if="getHistoryCount(win.key) > 0" class="sb-memory-track">
          <span
            v-for="(hid, idx) in getHistory(win.key)"
            :key="hid"
            class="sb-mem-dot"
            :class="{ 'sb-mem-dot-active': idx === getHistory(win.key).length - 1, 'sb-mem-dot-new': idx === getHistory(win.key).length - 1 && getState(win.key).isNew }"
            :title="getSceneName(hid)"
          />
        </div>
      </div>

      <!-- 场景名（打字机效果轮换） -->
      <div class="sb-name" :class="{ 'sb-name-on': getLatestScene(win.key) && getState(win.key).visible }">
        <span v-if="getLatestScene(win.key)" class="sb-name-text">▸ {{ getLatestScene(win.key)!.name }}</span>
      </div>

      <div v-if="win.key !== 'family'" class="sb-sep" />
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * 三分镜像素场景组件 (v4 - 累积式记忆版)
 *
 * 三个窗口并列：💼事业(绿) / ☕生活(青) / 🏠家庭(粉)
 * 当年触发的剧情事件，次年在对应窗口展示像素动画演绎。
 *
 * v4核心改进 - 累积式分镜：
 * - 场景不再被替换，而是"沉淀"累积
 * - 主画面显示最新事件，旧场景变为半透明残影叠加
 * - 底部记忆轨迹条：小圆点标记每个历史事件
 * - 新事件入场有更强烈的"加入"动画
 * - 事件计数标签显示累计事件数
 * - 63+像素场景，CSS box-shadow渲染
 * - 环境漂浮粒子、CRT故障、色差分离
 * - 场景专属微动效（火焰、炊烟、雨丝、爱心等）
 */

import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { useGameStore } from '../../store/game.store.js'
import { getSceneById, type StoryboardScene } from '../../data/storyboard-scenes.js'

const store = useGameStore()

// ================================================================
//  分镜队列（累积式，每个分类保存历史场景id列表）
// ================================================================

const storyboards = computed(() => {
  const sb = (store as any).pendingStoryboards
  if (!sb) return { family: [], life: [], career: [] }
  return {
    family: (sb.family || []) as string[],
    life: (sb.life || []) as string[],
    career: (sb.career || []) as string[],
  }
})

// 年份显示
const currentYear = computed(() => {
  const age = store.state.currentAge
  return 2024 + (age - 22)
})

// ================================================================
//  窗口配置
// ================================================================
interface WindowConfig {
  key: 'family' | 'life' | 'career'
  icon: string
  label: string
  subtitle: string
  themeColor: string
  glowColor: string
  borderColor: string
  delay: number
}

const windows: WindowConfig[] = [
  { key: 'career', icon: '💼', label: '事业', subtitle: 'CAREER', themeColor: '#00ff88', glowColor: 'rgba(0,255,136,0.5)', borderColor: 'rgba(0,255,136,0.12)', delay: 0 },
  { key: 'life',   icon: '☕', label: '生活', subtitle: 'LIFE',   themeColor: '#00d4ff', glowColor: 'rgba(0,212,255,0.5)', borderColor: 'rgba(0,212,255,0.12)', delay: 180 },
  { key: 'family', icon: '🏠', label: '家庭', subtitle: 'FAMILY', themeColor: '#ff8ab8', glowColor: 'rgba(255,138,184,0.5)', borderColor: 'rgba(255,138,184,0.12)', delay: 360 },
]

// ================================================================
//  像素渲染
// ================================================================

const PIXEL_SIZE = 5

function buildPixelShadows(scene: StoryboardScene): string {
  const shadows: string[] = []
  const { pixels, palette } = scene
  for (let row = 0; row < pixels.length; row++) {
    for (let col = 0; col < pixels[row].length; col++) {
      const ci = pixels[row][col]
      if (ci === 0) continue
      const color = palette[ci]
      if (!color || color === 'transparent') continue
      shadows.push(`${col * PIXEL_SIZE}px ${row * PIXEL_SIZE}px 0 0 ${color}`)
    }
  }
  return shadows.join(', ')
}

function getSceneStyle(scene: StoryboardScene) {
  return {
    width: 16 * PIXEL_SIZE + 'px',
    height: 12 * PIXEL_SIZE + 'px',
    boxShadow: buildPixelShadows(scene),
  }
}

// ================================================================
//  动画状态
// ================================================================

interface WinState {
  /** 当前主场景 */
  scene: StoryboardScene | null
  /** 上一个场景（用于过渡） */
  prevScene: StoryboardScene | null
  /** 主场景是否可见 */
  visible: boolean
  /** 粒子爆发 */
  burst: boolean
  /** 窗口故障 */
  glitch: boolean
  /** 是否为新加入的事件（控制入场动画强度） */
  isNew: boolean
}

const states = ref<Record<string, WinState>>({
  family:  { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false },
  life:    { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false },
  career:  { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false },
})

const prevLatestIds = ref<Record<string, string | null>>({
  family: null, life: null, career: null,
})

// 全局CRT故障效果
const globalGlitch = ref(false)
let glitchTimer: number | null = null

function scheduleGlitch() {
  if (glitchTimer) clearTimeout(glitchTimer)
  const nextGlitch = 8000 + Math.random() * 17000
  glitchTimer = window.setTimeout(() => {
    globalGlitch.value = true
    setTimeout(() => { globalGlitch.value = false }, 180)
    scheduleGlitch()
  }, nextGlitch)
}

function playStoryboards() {
  for (const win of windows) {
    const key = win.key
    const history = getHistory(key)
    const latestId = history.length > 0 ? history[history.length - 1] : null
    const latestScene = latestId ? (getSceneById(latestId) || null) : null
    const st = states.value[key]
    const prevId = prevLatestIds.value[key]

    if (latestId === prevId) {
      st.visible = true
      st.isNew = false
      continue
    }

    // 新事件到来
    st.prevScene = st.scene
    st.visible = false
    st.isNew = true

    setTimeout(() => {
      st.scene = latestScene
      prevLatestIds.value[key] = latestId
      st.visible = true
      if (latestScene) {
        st.burst = true
        setTimeout(() => { st.burst = false }, 900)
        setTimeout(() => {
          st.glitch = true
          setTimeout(() => { st.glitch = false }, 220)
        }, 500 + win.delay)
        // "新加入"标记持续一段时间后消失
        setTimeout(() => { st.isNew = false }, 2000)
      }
    }, win.delay + 150)
  }
}

watch(() => store.state.currentAge, () => { setTimeout(playStoryboards, 400) })
watch(() => [storyboards.value.family.length, storyboards.value.life.length, storyboards.value.career.length], () => { setTimeout(playStoryboards, 400) })
onMounted(() => {
  setTimeout(playStoryboards, 600)
  scheduleGlitch()
})
onUnmounted(() => {
  if (glitchTimer) clearTimeout(glitchTimer)
})

// ================================================================
//  累积式辅助函数
// ================================================================

function getState(key: string): WinState {
  return states.value[key] || { scene: null, prevScene: null, visible: false, burst: false, glitch: false, isNew: false }
}

/** 获取某分类的历史场景id列表 */
function getHistory(key: string): string[] {
  return (storyboards.value as any)[key] || []
}

/** 获取历史事件数量 */
function getHistoryCount(key: string): number {
  return getHistory(key).length
}

/** 获取最新（当前主）场景 */
function getLatestScene(key: string): StoryboardScene | null {
  const hist = getHistory(key)
  if (hist.length === 0) return null
  return getSceneById(hist[hist.length - 1]) || null
}

/** 获取残影场景（除最新外的旧场景，最多显示2个残影） */
function getGhostScenes(key: string): StoryboardScene[] {
  const hist = getHistory(key)
  if (hist.length <= 1) return []
  // 取倒数第2、第3个作为残影（最多2个），越旧越透明
  const ghosts: StoryboardScene[] = []
  for (let i = hist.length - 2; i >= Math.max(0, hist.length - 3); i--) {
    const s = getSceneById(hist[i])
    if (s) ghosts.push(s)
  }
  return ghosts
}

function hasTrigger(key: string): boolean {
  return getHistoryCount(key) > 0
}

function getSceneName(id: string): string {
  const s = getSceneById(id)
  return s ? s.name : id
}

function idleClass(scene: StoryboardScene | null): string {
  if (!scene) return ''
  return 'sb-idle-' + (scene.idleAnim || 'breath')
}

// 获取场景专属特效class
function sceneEffectClass(scene: StoryboardScene | null): string {
  if (!scene) return ''
  const effects: Record<string, string> = {
    house: 'sb-effect-smoke',
    car: 'sb-effect-speed',
    marriage: 'sb-effect-hearts',
    baby: 'sb-effect-twinkle',
    birthday: 'sb-effect-flame',
    sickness: 'sb-effect-heartbeat',
    parent_sick: 'sb-effect-heartbeat',
    health_check: 'sb-effect-heartbeat',
    work: 'sb-effect-screen',
    investment: 'sb-effect-chart',
    startup: 'sb-effect-flames',
    bankruptcy: 'sb-effect-shake',
    fired: 'sb-effect-paper-fall',
    friend_drink: 'sb-effect-bubbles',
    travel: 'sb-effect-clouds',
    fishing: 'sb-effect-water',
    rain: 'sb-effect-rain',
    square_dance: 'sb-effect-notes',
    lottery: 'sb-effect-coins',
    bonus: 'sb-effect-coins',
    promotion: 'sb-effect-stars',
    inheritance: 'sb-effect-shine',
    house_price_up: 'sb-effect-stars',
    ai_breakthrough: 'sb-effect-neural',
    cyberbullying: 'sb-effect-glitch-text',
    pills: 'sb-effect-pills',
    hair_loss: 'sb-effect-shock',
    scam: 'sb-effect-alert',
    inflation: 'sb-effect-up',
    car_accident: 'sb-effect-crash',
    funeral: 'sb-effect-candle',
    anniversary: 'sb-effect-flame',
    date: 'sb-effect-candle',
    midnight_baby: 'sb-effect-zzz',
    old_couple_tv: 'sb-effect-tv',
    balcony_garden: 'sb-effect-grow',
    stray_cat: 'sb-effect-heart-small',
    couple_fight: 'sb-effect-lightning',
    mother_in_law: 'sb-effect-lightning',
    homework: 'sb-effect-anger',
    faith_crisis: 'sb-effect-rain',
    midlife_crisis: 'sb-effect-mirror',
    seven_year_itch: 'sb-effect-distance',
    divorce: 'sb-effect-broken',
    therapy: 'sb-effect-tissue',
    office_politics: 'sb-effect-dark',
    side_hustle: 'sb-effect-spark',
    burnout: 'sb-effect-fog',
    gym: 'sb-effect-flex',
    exam: 'sb-effect-brain',
    pet: 'sb-effect-paw',
    plant: 'sb-effect-leaf',
    reading: 'sb-effect-book',
    concert: 'sb-effect-wave',
    reunion: 'sb-effect-cheers',
    debt: 'sb-effect-down',
    stock_crash: 'sb-effect-down',
    crypto_crash: 'sb-effect-down',
    hospital: 'sb-effect-cross',
    checkup: 'sb-effect-cross',
    volunteer: 'sb-effect-sun',
    donate: 'sb-effect-sun',
    yoga: 'sb-effect-lotus',
    meditation: 'sb-effect-lotus',
    gray_hair: 'sb-effect-silver',
    retirement_party: 'sb-effect-confetti',
    grandchildren: 'sb-effect-stars-small',
  }
  return effects[scene.id] || ''
}

// 粒子数量
const PARTICLES_PER_WIN = 6
const particles = Array.from({ length: PARTICLES_PER_WIN }, (_, i) => i)
</script>

<style scoped>
/* ===== 容器 ===== */
.storyboard-scene {
  position: absolute;
  inset: 0;
  display: flex;
  gap: 0;
  background: #050608;
  overflow: hidden;
}

.sb-scanlines {
  position: absolute;
  inset: 0;
  background: repeating-linear-gradient(
    0deg, transparent, transparent 1px,
    rgba(0,0,0,0.12) 1px, rgba(0,0,0,0.12) 2px
  );
  pointer-events: none;
  z-index: 20;
  opacity: 0.6;
}

/* 噪点层 */
.sb-noise {
  position: absolute;
  inset: 0;
  z-index: 19;
  pointer-events: none;
  opacity: 0.03;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
  animation: noiseShift 0.5s steps(2) infinite;
}
@keyframes noiseShift {
  0% { transform: translate(0, 0); }
  25% { transform: translate(-1px, 1px); }
  50% { transform: translate(1px, -1px); }
  75% { transform: translate(-1px, -1px); }
  100% { transform: translate(1px, 1px); }
}

/* 全局故障 */
.sb-global-glitch {
  animation: globalGlitch 0.18s steps(2);
}
.sb-global-glitch .sb-window {
  animation: winGlitch 0.18s steps(2);
}
@keyframes globalGlitch {
  0% { transform: translate(0); filter: hue-rotate(0deg); }
  20% { transform: translate(-2px, 1px); filter: hue-rotate(30deg); }
  40% { transform: translate(2px, -1px); filter: hue-rotate(-30deg); }
  60% { transform: translate(-1px, 2px); filter: hue-rotate(15deg); }
  80% { transform: translate(1px, -2px); filter: hue-rotate(-15deg); }
  100% { transform: translate(0); filter: hue-rotate(0deg); }
}
@keyframes winGlitch {
  0%,100% { transform: skewX(0deg); }
  25% { transform: skewX(-2deg); }
  75% { transform: skewX(2deg); }
}

/* ===== 窗口 ===== */
.sb-window {
  flex: 1;
  position: relative;
  display: flex;
  flex-direction: column;
  background: linear-gradient(180deg, rgba(10,12,16,0.95) 0%, rgba(5,6,8,0.98) 100%);
  border-right: 1px solid var(--b);
  overflow: hidden;
  transition: flex 0.6s ease;
}
.sb-window:last-child { border-right: none; }
.sb-window.is-on {
  background: linear-gradient(180deg, rgba(12,15,20,0.9) 0%, rgba(6,8,12,0.95) 100%);
}

/* 霓虹边框 */
.sb-neon {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 10;
  opacity: 0;
  transition: opacity 0.6s;
  box-shadow: inset 0 0 0 1px var(--c), inset 0 0 20px var(--g);
}
.sb-window.is-on .sb-neon { opacity: 0.7; animation: neonBreath 3s ease-in-out infinite; }
@keyframes neonBreath {
  0%,100% { opacity: 0.5; }
  50% { opacity: 0.85; }
}

/* 色差分离 */
.sb-chroma {
  position: absolute;
  inset: 0;
  pointer-events: none;
  z-index: 11;
  opacity: 0;
  background:
    linear-gradient(90deg, rgba(255,0,80,0.03) 0%, transparent 40%, transparent 60%, rgba(0,200,255,0.03) 100%);
  mix-blend-mode: screen;
}
.sb-window.is-glitch .sb-chroma {
  opacity: 1;
  animation: chromaShift 0.22s steps(3);
}
@keyframes chromaShift {
  0% { transform: translateX(0); }
  33% { transform: translateX(-2px); }
  66% { transform: translateX(2px); }
  100% { transform: translateX(0); }
}

/* 顶栏 */
.sb-topbar {
  position: relative;
  z-index: 12;
  display: flex;
  align-items: center;
  gap: 5px;
  padding: 4px 7px;
  background: linear-gradient(180deg, rgba(0,0,0,0.5) 0%, transparent 100%);
  border-bottom: 1px solid var(--b);
  font-family: 'Courier New', 'Consolas', monospace;
  font-size: 9px;
  letter-spacing: 0.5px;
  flex-shrink: 0;
}
.sb-ico { font-size: 10px; }
.sb-txt { color: var(--c); font-weight: bold; font-size: 10px; }
.sb-sub { color: rgba(255,255,255,0.3); font-size: 8px; letter-spacing: 1px; }
.sb-yr {
  margin-left: auto;
  color: rgba(255,255,255,0.35);
  font-size: 8px;
}
.sb-rec {
  width: 6px; height: 6px;
  border-radius: 50%;
  background: #ff3355;
  animation: recBlink 1.2s ease-in-out infinite;
  box-shadow: 0 0 6px #ff3355;
}
@keyframes recBlink {
  0%,100% { opacity: 1; }
  50% { opacity: 0.3; }
}
.sb-count {
  min-width: 14px;
  height: 14px;
  line-height: 14px;
  text-align: center;
  border-radius: 3px;
  background: var(--c);
  color: #000;
  font-size: 8px;
  font-weight: bold;
  box-shadow: 0 0 6px var(--g);
}

/* ===== 舞台 ===== */
.sb-stage {
  flex: 1;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  min-height: 0;
}

.sb-vignette {
  position: absolute;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background: radial-gradient(ellipse at center, transparent 40%, rgba(0,0,0,0.5) 100%);
}

/* 漂浮粒子 */
.sb-particles {
  position: absolute;
  inset: 0;
  z-index: 2;
  pointer-events: none;
  overflow: hidden;
}
.sb-particle {
  position: absolute;
  width: 2px;
  height: 2px;
  background: var(--c);
  border-radius: 50%;
  opacity: 0;
  left: calc(10% + var(--i) * 14%);
  bottom: -5px;
  animation: particleFloat var(--dur) ease-in-out infinite;
  animation-delay: var(--delay);
  box-shadow: 0 0 4px var(--c);
}
.sb-window.is-empty .sb-particle { display: none; }
@keyframes particleFloat {
  0% { transform: translateY(0) translateX(0); opacity: 0; }
  10% { opacity: 0.4; }
  50% { transform: translateY(-60px) translateX(5px); opacity: 0.6; }
  90% { opacity: 0.2; }
  100% { transform: translateY(-120px) translateX(-3px); opacity: 0; }
}

/* 记忆残影层（旧场景半透明叠加，体现累积感） */
.sb-memory-layer {
  position: absolute;
  inset: 0;
  z-index: 3;
  display: flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
}
.sb-ghost {
  position: absolute;
  opacity: 0;
  filter: grayscale(0.8) brightness(0.5);
}
.sb-ghost-0 {
  opacity: 0.12;
  transform: scale(0.85) translate(-8px, 3px);
  animation: ghostDrift1 8s ease-in-out infinite;
}
.sb-ghost-1 {
  opacity: 0.07;
  transform: scale(0.7) translate(10px, -5px);
  animation: ghostDrift2 10s ease-in-out infinite;
}
@keyframes ghostDrift1 {
  0%,100% { transform: scale(0.85) translate(-8px, 3px); opacity: 0.12; }
  50% { transform: scale(0.88) translate(-10px, 1px); opacity: 0.16; }
}
@keyframes ghostDrift2 {
  0%,100% { transform: scale(0.7) translate(10px, -5px); opacity: 0.07; }
  50% { transform: scale(0.73) translate(12px, -7px); opacity: 0.1; }
}

/* 待机 */
.sb-standby {
  position: relative;
  z-index: 4;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  opacity: 0.25;
}
.sb-standby-dot {
  width: 8px; height: 8px;
  border-radius: 50%;
  border: 1px solid var(--c);
  animation: standbyPulse 2s ease-in-out infinite;
}
@keyframes standbyPulse {
  0%,100% { opacity: 0.3; box-shadow: 0 0 4px var(--c); }
  50% { opacity: 0.8; box-shadow: 0 0 12px var(--c); }
}
.sb-standby-line {
  width: 40px; height: 1px;
  background: linear-gradient(90deg, transparent, var(--c), transparent);
}
.sb-standby-text {
  font-family: 'Courier New', monospace;
  font-size: 7px;
  color: var(--c);
  letter-spacing: 2px;
}

/* 像素艺术画布 */
.sb-art-wrap {
  position: absolute;
  z-index: 5;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.5s ease;
}
.sb-art-wrap.sb-in { opacity: 1; }
.sb-art-wrap.sb-art-old {
  z-index: 4;
  opacity: 0;
  animation: oldFadeOut 0.6s ease-out forwards;
}
@keyframes oldFadeOut {
  0% { opacity: 1; transform: scale(1); filter: brightness(1); }
  100% { opacity: 0; transform: scale(0.9) translateY(5px); filter: brightness(0.3) blur(2px); }
}
.sb-art-wrap.sb-new .sb-art-scale {
  animation: newJoin 0.9s cubic-bezier(0.34,1.56,0.64,1);
}
@keyframes newJoin {
  0% { transform: scale(0.3) rotate(-8deg); filter: brightness(3); }
  40% { transform: scale(1.15) rotate(2deg); filter: brightness(1.8); }
  70% { transform: scale(0.95) rotate(-1deg); filter: brightness(1.2); }
  100% { transform: scale(1) rotate(0deg); filter: brightness(1); }
}

.sb-art-scale {
  position: relative;
  transform-origin: center bottom;
}
.sb-art {
  position: relative;
  transform-origin: center bottom;
  image-rendering: pixelated;
}

/* 入场动画 */
.sb-anim-fade {
  opacity: 0;
  animation: aFade 0.7s ease-out forwards;
  animation-delay: var(--d);
}
@keyframes aFade {
  to { opacity: 1; }
}

.sb-anim-rise {
  opacity: 0;
  transform: translateY(12px);
  animation: aRise 0.8s cubic-bezier(0.22,1,0.36,1) forwards;
  animation-delay: var(--d);
}
@keyframes aRise {
  to { opacity: 1; transform: translateY(0); }
}

.sb-anim-pop {
  opacity: 0;
  transform: scale(0.1);
  animation: aPop 0.8s cubic-bezier(0.34,1.56,0.64,1) forwards;
  animation-delay: var(--d);
}
@keyframes aPop {
  0%   { opacity: 0; transform: scale(0.1); filter: brightness(5); }
  50%  { opacity: 1; transform: scale(1.25); filter: brightness(2); }
  72%  { transform: scale(0.9); filter: brightness(1.4); }
  85%  { transform: scale(1.05); filter: brightness(1.1); }
  100% { opacity: 1; transform: scale(1); filter: brightness(1); }
}

.sb-anim-slide {
  opacity: 0;
  transform: translateX(24px);
  animation: aSlide 0.85s cubic-bezier(0.22,1,0.36,1) forwards;
  animation-delay: var(--d);
}
@keyframes aSlide {
  0%   { opacity: 0; transform: translateX(24px); filter: blur(3px); }
  100% { opacity: 1; transform: translateX(0); filter: blur(0); }
}

.sb-anim-blink {
  opacity: 0;
  animation: aBlink 0.5s steps(5) forwards, aShock 2.5s ease-in-out 0.6s infinite;
  animation-delay: var(--d);
}
@keyframes aBlink {
  0%   { opacity: 0; }
  40%  { opacity: 1; }
  60%  { opacity: 0; }
  80%  { opacity: 1; }
  100% { opacity: 1; }
}
@keyframes aShock {
  0%,100% { filter: brightness(1) drop-shadow(0 0 8px var(--c)); }
  50%     { filter: brightness(1.5) drop-shadow(0 0 18px var(--c)); }
}

.sb-anim-shake {
  opacity: 0;
  transform: scale(0.85);
  animation: aShakeIn 0.5s ease-out forwards, aShake 0.3s ease-in-out 0.6s 3;
  animation-delay: var(--d);
}
@keyframes aShakeIn {
  0%   { opacity: 0; transform: scale(0.85); }
  100% { opacity: 1; transform: scale(1); }
}
@keyframes aShake {
  0%,100% { transform: translateX(0); }
  20%     { transform: translateX(-3px); }
  40%     { transform: translateX(3px); }
  60%     { transform: translateX(-2px); }
  80%     { transform: translateX(2px); }
}

/* 持续微动效 */
.sb-idle-breath {
  animation: idleBreath 4s ease-in-out infinite;
  animation-delay: calc(var(--d) + 1s);
}
@keyframes idleBreath {
  0%,100% { transform: scale(1); filter: drop-shadow(0 0 5px var(--g)) brightness(1); }
  50%     { transform: scale(1.05); filter: drop-shadow(0 0 12px var(--g)) brightness(1.15); }
}

.sb-idle-flicker {
  animation: idleBreath 4s ease-in-out infinite, idleFlicker 7s ease-in-out infinite;
  animation-delay: calc(var(--d) + 1s);
}
@keyframes idleFlicker {
  0%,100% { filter: drop-shadow(0 0 4px var(--g)) brightness(1); }
  5%      { filter: drop-shadow(0 0 2px var(--g)) brightness(0.6); }
  8%      { filter: drop-shadow(0 0 10px var(--g)) brightness(1.3); }
  11%     { filter: drop-shadow(0 0 4px var(--g)) brightness(1); }
  45%     { filter: drop-shadow(0 0 4px var(--g)) brightness(1); }
  47%     { filter: drop-shadow(0 0 2px var(--g)) brightness(0.7); }
  50%     { filter: drop-shadow(0 0 4px var(--g)) brightness(1); }
  82%     { filter: drop-shadow(0 0 4px var(--g)) brightness(1); }
  84%     { filter: drop-shadow(0 0 2px var(--g)) brightness(0.8); }
  86%     { filter: drop-shadow(0 0 4px var(--g)) brightness(1); }
}

.sb-idle-float {
  animation: idleFloat 3.5s ease-in-out infinite;
  animation-delay: calc(var(--d) + 1s);
}
@keyframes idleFloat {
  0%,100% { transform: translateY(0); filter: drop-shadow(0 0 4px var(--g)); }
  50%     { transform: translateY(-4px); filter: drop-shadow(0 0 10px var(--g)); }
}

.sb-idle-sway {
  animation: idleSway 4s ease-in-out infinite;
  animation-delay: calc(var(--d) + 1s);
  transform-origin: bottom center;
}
@keyframes idleSway {
  0%,100% { transform: rotate(0deg); }
  25%     { transform: rotate(-2deg); }
  75%     { transform: rotate(2deg); }
}

.sb-idle-blink-slow {
  animation: idleBlink 5s ease-in-out infinite;
  animation-delay: calc(var(--d) + 1s);
}
@keyframes idleBlink {
  0%,92%,100% { opacity: 1; }
  95% { opacity: 0.3; }
}

.sb-idle-none {}

/* 粒子爆发 */
.sb-burst {
  position: absolute;
  z-index: 8;
  inset: 0;
  pointer-events: none;
}
.sb-burst-p {
  position: absolute;
  left: 50%;
  top: 50%;
  width: 4px;
  height: 4px;
  background: var(--c);
  border-radius: 50%;
  box-shadow: 0 0 8px var(--c), 0 0 16px var(--g);
  animation: burstOut 0.9s ease-out forwards;
  --angle: calc(var(--i) * 22.5deg);
  --dist: 30px;
}
@keyframes burstOut {
  0% {
    transform: translate(-50%, -50%) rotate(var(--angle)) translateX(0) scale(1);
    opacity: 1;
  }
  100% {
    transform: translate(-50%, -50%) rotate(var(--angle)) translateX(var(--dist)) scale(0);
    opacity: 0;
  }
}

/* 光晕 */
.sb-glow {
  position: absolute;
  z-index: 0;
  width: 80px;
  height: 80px;
  border-radius: 50%;
  background: radial-gradient(circle, var(--g) 0%, transparent 70%);
  opacity: 0.3;
  animation: glowPulse 3s ease-in-out infinite;
  pointer-events: none;
  filter: blur(8px);
}
@keyframes glowPulse {
  0%,100% { opacity: 0.2; transform: scale(1); }
  50% { opacity: 0.5; transform: scale(1.3); }
}

/* 记忆轨迹条 */
.sb-memory-track {
  position: absolute;
  bottom: 4px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 9;
  display: flex;
  gap: 4px;
  align-items: center;
  padding: 2px 6px;
  background: rgba(0,0,0,0.5);
  border-radius: 6px;
}
.sb-mem-dot {
  width: 5px;
  height: 5px;
  border-radius: 50%;
  background: rgba(255,255,255,0.15);
  border: 1px solid rgba(255,255,255,0.2);
  transition: all 0.3s;
}
.sb-mem-dot-active {
  background: var(--c);
  border-color: var(--c);
  box-shadow: 0 0 6px var(--c);
}
.sb-mem-dot-new {
  animation: memDotNew 1.5s ease-out;
}
@keyframes memDotNew {
  0% { transform: scale(2.5); box-shadow: 0 0 12px var(--c); }
  50% { transform: scale(1.5); }
  100% { transform: scale(1); box-shadow: 0 0 6px var(--c); }
}

/* 场景名 */
.sb-name {
  position: relative;
  z-index: 12;
  padding: 3px 7px;
  border-top: 1px solid var(--b);
  background: linear-gradient(0deg, rgba(0,0,0,0.6) 0%, transparent 100%);
  min-height: 18px;
  flex-shrink: 0;
}
.sb-name-text {
  font-family: 'Courier New', monospace;
  font-size: 8px;
  color: rgba(255,255,255,0.4);
  opacity: 0;
  transform: translateY(4px);
  transition: all 0.5s ease;
  letter-spacing: 0.5px;
}
.sb-name-on .sb-name-text {
  opacity: 1;
  transform: translateY(0);
  color: var(--c);
  text-shadow: 0 0 8px var(--g);
}

.sb-sep {
  position: absolute;
  right: 0;
  top: 10%;
  bottom: 10%;
  width: 1px;
  background: linear-gradient(180deg, transparent, rgba(255,255,255,0.08), transparent);
  z-index: 15;
}

/* ===== 场景专属特效 ===== */
.sb-effect-layer {
  position: absolute;
  inset: 0;
  pointer-events: none;
}

/* 炊烟 */
.sb-effect-smoke::after {
  content: '';
  position: absolute;
  width: 4px; height: 4px;
  background: rgba(200,200,200,0.4);
  border-radius: 50%;
  top: -8px; right: 20px;
  animation: smokeRise 3s ease-out infinite;
}
@keyframes smokeRise {
  0% { transform: translateY(0) scale(1); opacity: 0.6; }
  100% { transform: translateY(-20px) scale(2.5); opacity: 0; }
}

/* 火焰 */
.sb-effect-flame::after {
  content: '';
  position: absolute;
  width: 4px; height: 6px;
  background: radial-gradient(ellipse at bottom, #ffdd00, #ff6600, transparent);
  border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%;
  top: -10px; left: 50%;
  margin-left: -2px;
  animation: flameFlicker 0.5s ease-in-out infinite alternate;
  filter: blur(0.5px);
}
@keyframes flameFlicker {
  0% { transform: scale(1) rotate(-2deg); opacity: 0.9; }
  100% { transform: scale(1.15) rotate(2deg); opacity: 1; }
}

/* 雨丝 */
.sb-effect-rain::after {
  content: '';
  position: absolute;
  inset: 0;
  background: repeating-linear-gradient(
    100deg,
    transparent, transparent 8px,
    rgba(0,212,255,0.15) 8px, rgba(0,212,255,0.15) 9px
  );
  animation: rainFall 0.3s linear infinite;
}
@keyframes rainFall {
  0% { transform: translateY(-5px); }
  100% { transform: translateY(5px); }
}

/* 爱心飘升 */
.sb-effect-hearts::after, .sb-effect-heart-small::after {
  content: '♥';
  position: absolute;
  font-size: 8px;
  color: var(--c);
  top: 0; left: 50%;
  opacity: 0;
  animation: heartFloat 3s ease-in-out infinite;
  text-shadow: 0 0 6px var(--c);
}
@keyframes heartFloat {
  0% { transform: translateY(0) scale(0.5); opacity: 0; }
  20% { opacity: 0.8; }
  100% { transform: translateY(-30px) scale(1.2); opacity: 0; }
}

/* 星星闪烁 */
.sb-effect-twinkle::before, .sb-effect-twinkle::after {
  content: '✦';
  position: absolute;
  font-size: 6px;
  color: #ffdd88;
  animation: twinkle 2s ease-in-out infinite;
  text-shadow: 0 0 6px #ffdd88;
}
.sb-effect-twinkle::before { top: -5px; left: -5px; animation-delay: 0s; }
.sb-effect-twinkle::after { top: -8px; right: -3px; animation-delay: 1s; }
@keyframes twinkle {
  0%,100% { opacity: 0.3; transform: scale(0.8); }
  50% { opacity: 1; transform: scale(1.2); }
}

/* 心跳（生病/医院） */
.sb-effect-heartbeat::after {
  content: '♥';
  position: absolute;
  font-size: 10px;
  color: #ff4466;
  top: 50%; left: 50%;
  margin: -20px 0 0 -5px;
  animation: heartbeat 0.8s ease-in-out infinite;
  text-shadow: 0 0 8px #ff4466;
  opacity: 0.7;
}
@keyframes heartbeat {
  0%,100% { transform: scale(1); }
  15% { transform: scale(1.3); }
  30% { transform: scale(1); }
  45% { transform: scale(1.2); }
}

/* 气泡（喝酒） */
.sb-effect-bubbles::after {
  content: '';
  position: absolute;
  width: 3px; height: 3px;
  border-radius: 50%;
  border: 1px solid rgba(255,255,255,0.4);
  bottom: 0; left: 50%;
  animation: bubbleUp 2s ease-out infinite;
}
@keyframes bubbleUp {
  0% { transform: translateY(0) scale(1); opacity: 0.6; }
  100% { transform: translateY(-25px) scale(0.3); opacity: 0; }
}

/* 云朵飘过（旅行） */
.sb-effect-clouds::before {
  content: '☁';
  position: absolute;
  font-size: 8px;
  top: -5px; left: -20px;
  color: rgba(255,255,255,0.3);
  animation: cloudDrift 8s linear infinite;
}
@keyframes cloudDrift {
  0% { transform: translateX(0); opacity: 0; }
  20% { opacity: 0.5; }
  80% { opacity: 0.5; }
  100% { transform: translateX(100px); opacity: 0; }
}

/* 水波纹（钓鱼） */
.sb-effect-water::after {
  content: '';
  position: absolute;
  width: 20px; height: 6px;
  bottom: -2px; left: 50%;
  margin-left: -10px;
  border: 1px solid rgba(0,150,255,0.4);
  border-radius: 50%;
  animation: waterRipple 2s ease-out infinite;
}
@keyframes waterRipple {
  0% { transform: scale(0.5); opacity: 0.8; }
  100% { transform: scale(2); opacity: 0; }
}

/* 音符（广场舞） */
.sb-effect-notes::after {
  content: '♪';
  position: absolute;
  font-size: 8px;
  color: var(--c);
  top: -5px; right: 0;
  opacity: 0;
  animation: noteFloat 2.5s ease-in-out infinite;
  text-shadow: 0 0 6px var(--c);
}
@keyframes noteFloat {
  0% { transform: translateY(0) rotate(0deg); opacity: 0; }
  30% { opacity: 0.8; }
  100% { transform: translateY(-20px) rotate(15deg); opacity: 0; }
}

/* 金币掉落（彩票/奖金） */
.sb-effect-coins::before {
  content: '¥';
  position: absolute;
  font-size: 8px;
  color: #ffdd00;
  font-weight: bold;
  top: -10px;
  animation: coinDrop 1.5s ease-in infinite;
  text-shadow: 0 0 6px #ffdd00;
}
@keyframes coinDrop {
  0% { transform: translateY(-10px) rotate(0deg); opacity: 0; }
  20% { opacity: 1; }
  100% { transform: translateY(30px) rotate(360deg); opacity: 0; }
}

/* 星星爆发（升职/涨价） */
.sb-effect-stars::before, .sb-effect-stars-small::before {
  content: '★';
  position: absolute;
  color: #ffdd00;
  animation: starBurst 1s ease-out;
  text-shadow: 0 0 8px #ffdd00;
}
.sb-effect-stars::before { font-size: 10px; top: -8px; left: 50%; margin-left: -5px; }
.sb-effect-stars-small::before { font-size: 7px; top: -5px; left: 50%; margin-left: -3px; }
@keyframes starBurst {
  0% { transform: scale(0) rotate(0deg); opacity: 1; }
  50% { transform: scale(1.5) rotate(180deg); opacity: 1; }
  100% { transform: scale(0.5) rotate(360deg); opacity: 0; }
}

/* 闪电（吵架/婆媳） */
.sb-effect-lightning::after {
  content: '⚡';
  position: absolute;
  font-size: 12px;
  top: -10px; left: 50%;
  margin-left: -6px;
  opacity: 0;
  animation: lightning 3s ease-in-out infinite;
  text-shadow: 0 0 10px #ffee00;
}
@keyframes lightning {
  0%,90%,100% { opacity: 0; }
  92% { opacity: 1; }
  94% { opacity: 0.3; }
  96% { opacity: 1; }
}

/* 蜡烛（葬礼/纪念日） */
.sb-effect-candle::after {
  content: '';
  position: absolute;
  width: 3px; height: 5px;
  background: radial-gradient(ellipse at bottom, #ffddaa, #ff8800, transparent);
  border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%;
  top: -8px; left: 50%;
  margin-left: -1px;
  animation: flameFlicker 0.6s ease-in-out infinite alternate;
}

/* ZZZ（熬夜带娃） */
.sb-effect-zzz::after {
  content: 'Z z';
  position: absolute;
  font-size: 7px;
  color: rgba(255,255,255,0.5);
  top: -8px; right: 0;
  animation: zzzFloat 3s ease-out infinite;
}
@keyframes zzzFloat {
  0% { transform: translate(0,0) scale(0.8); opacity: 0; }
  30% { opacity: 0.6; }
  100% { transform: translate(8px,-15px) scale(1.2); opacity: 0; }
}

/* 其余特效的轻量版本 */
.sb-effect-speed::after, .sb-effect-screen::after, .sb-effect-chart::after,
.sb-effect-flames::after, .sb-effect-shake::after, .sb-effect-paper-fall::after,
.sb-effect-shine::after, .sb-effect-neural::after, .sb-effect-glitch-text::after,
.sb-effect-pills::after, .sb-effect-shock::after, .sb-effect-alert::after,
.sb-effect-up::after, .sb-effect-crash::after, .sb-effect-tv::after,
.sb-effect-grow::after, .sb-effect-mirror::after, .sb-effect-distance::after,
.sb-effect-broken::after, .sb-effect-tissue::after, .sb-effect-anger::after,
.sb-effect-dark::after, .sb-effect-spark::after, .sb-effect-fog::after,
.sb-effect-flex::after, .sb-effect-brain::after, .sb-effect-paw::after,
.sb-effect-leaf::after, .sb-effect-book::after, .sb-effect-wave::after,
.sb-effect-cheers::after, .sb-effect-down::after, .sb-effect-cross::after,
.sb-effect-sun::after, .sb-effect-lotus::after, .sb-effect-silver::after,
.sb-effect-confetti::after {
  content: '';
  position: absolute;
  inset: 0;
  pointer-events: none;
  opacity: 0.15;
  background: radial-gradient(circle at center, var(--c) 0%, transparent 70%);
  animation: genericPulse 3s ease-in-out infinite;
}
@keyframes genericPulse {
  0%,100% { opacity: 0.1; }
  50% { opacity: 0.25; }
}

/* ===== 响应式 ===== */
@media (max-width: 768px) {
  .sb-topbar { padding: 3px 5px; font-size: 7px; }
  .sb-ico { font-size: 8px; }
  .sb-txt { font-size: 8px; }
  .sb-sub { display: none; }
  .sb-name-text { font-size: 7px; }
  .sb-memory-track { gap: 3px; padding: 1px 4px; }
  .sb-mem-dot { width: 4px; height: 4px; }
}

@media (min-width: 1400px) {
  .sb-topbar { padding: 5px 10px; font-size: 10px; gap: 6px; }
  .sb-ico { font-size: 12px; }
  .sb-txt { font-size: 12px; }
  .sb-sub { font-size: 9px; }
  .sb-yr { font-size: 9px; }
  .sb-name { padding: 4px 10px; min-height: 22px; }
  .sb-name-text { font-size: 10px; }
  .sb-count { font-size: 9px; min-width: 16px; height: 16px; line-height: 16px; }
  .sb-rec { width: 7px; height: 7px; }
}

@media (min-width: 1900px) {
  .sb-topbar { padding: 6px 12px; font-size: 11px; gap: 8px; }
  .sb-ico { font-size: 14px; }
  .sb-txt { font-size: 14px; }
  .sb-sub { font-size: 10px; }
  .sb-name-text { font-size: 11px; }
}
</style>
